version: '2'
services:

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  moodle:
    image: erseco/alpine-moodle
    build: .
    restart: unless-stopped
    environment:
      DEV_MODE: "true"
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      SITE_URL: "http://localhost"
      DB_TYPE: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "moodle"
      DB_USER: "moodle"
      DB_PASS: "moodle"
      DB_PREFIX: "mdl_"
      SSLPROXY: "false"
      MOODLE_EMAIL: "user@example.com"
      MOODLE_LANGUAGE: "en"
      MOODLE_SITENAME: "New-Site"
      MOODLE_USERNAME: "moodleuser"
      MOODLE_PASSWORD: "PLEASE_CHANGEME"
      SMTP_HOST: "smtp"
      SMTP_PORT: "1025"
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_PROTOCOL: "tcp"
      MOODLE_MAIL_NOREPLY_ADDRESS: "noreply@localhost"
      MOODLE_MAIL_PREFIX: "[moodle]"
    ports:
      - 80:8080
    volumes:
      - moodledata:/var/www/moodledata
      - moodlehtml:/var/www/html
    depends_on:
      - postgres

  smtp:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp server


volumes:
  postgres: null
  moodledata: null
  moodlehtml: null
